version: '3.8'

services:
  server:
    build: .
    image: go-playfair-server
    container_name: playfair-server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/playfair-server
